ğŸ› ï¸ - Source Change:
  - all:
    - changed-files:
      - any-glob-to-any-file: 'Source/**/*.{ts|js}'
      - all-globs-to-all-files: '!Source/Typings/**/*'
      - all-globs-to-all-files: '!**/*.test.{js,ts}'
      - all-globs-to-all-files: '!**/*.spec.{js,ts}'

âœ¨ - Enhancement:
  - head-branch: ['^feature', 'feature/', '^feat', 'feat/']

ğŸ”§ - Fix:
  - head-branch: ['^bugfix', 'bugfix/', '^fix', 'fix/']

ğŸ“– - Documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', '**/*.mdx', 'docs/**/*']
  - head-branch: ['^docs', 'docs', 'documentation']